imageTag: "7.15.0"

fullnameOverride: "filebeat"

filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
    processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
    - decode_json_fields:
        fields: message
        process_array: false
        max_depth: 5
        target: "log_processed"
        overwrite_keys: false
        add_error_key: true
    - drop_fields:
        fields:
        - "log_processed.attr.command"
        - "log_processed.attr.error"
        - "log_processed.attr.CRUD"
        - "log_processed.id"
        ignore_missing: true
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'

resources:
  requests:
    cpu: 4000m
    memory: 4000Mi
  limits:
    cpu: 8000Mi
    memory: 8000Mi
