apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: false
    istiocoredns:
      enabled: false
    kiali:
      enabled: true
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: true
    tracing:
      enabled: true
  components:
    base:
      enabled: true
    proxy:
      enabled: true
      k8s:
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
    citadel:
      enabled: false
    cni:
      enabled: false
    egressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      name: istio-egressgateway
    galley:
      enabled: false
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      name: istio-ingressgateway
    nodeAgent:
      enabled: false
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 3
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
    policy:
      enabled: false
    sidecarInjector:
      enabled: false
    telemetry:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 5
        resources:
          limits:
            cpu: 4000m
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 128Mi
  hub: docker.io/istio
  tag: 1.5.2
  values:
    global:
      controlPlaneSecurityEnabled: false
      proxy:
        concurrency: 2
    kiali:
      createDemoSecret: true
    pilot:
      traceSampling: 10
    prometheusOperator:
      createPrometheusResource: false
