apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: docker.io/istio
  tag: 1.11.4
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 1000Mi
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 1000Mi
    egressGateways:
    - enabled: false
      name: istio-egressgateway
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 1000Mi
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 1000Mi
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 3
      autoscaleMin: 1
      cpu:
        targetAverageUtilization: 80
      traceSampling: 0
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        autoscaleMax: 5
        autoscaleMin: 1
        cpu:
          targetAverageUtilization: 80
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
