apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: docker.io/istio
  tag: 1.11.4
  components:
    proxy:
      k8s:
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 3
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      name: istio-ingressgateway
