imageTag: "7.15.0"

clusterName: "elasticsearch"

nodeGroup: "client"

replicas: 3

roles:
  master: "false"
  ingest: "false"
  data: "false"
  ml: "false"
  remote_cluster_client: "false"

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false

persistence:
  enabled: false

resources:
  requests:
    cpu: 4000m
    memory: 4000Mi
  limits:
    cpu: 4000m
    memory: 4000Mi
