image:
  tag: "6.8.20"

master:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 4000m
      memory: 4000Mi
    limits:
      cpu: 4000m
      memory: 4000Mi

data:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 16000m
      memory: 16000Mi
    limits:
      cpu: 32000m
      memory: 32000Mi

client:
  resources:
    requests:
      cpu: 4000m
      memory: 4000Mi
    limits:
      cpu: 16000m
      memory: 16000Mi
